/**
 * Canonical route paths (all lowercase).
 * Use these for Link href and redirects so routes match on case-sensitive systems (e.g. Linux/Vercel).
 */
export const routes = {
  home: "/",
  competition: "/competition",
  competitionId: (id: string) => `/competition/${id}`,
  results: "/results",
  resultsId: (id: string) => `/results/${id}`,
  lesson: "/lesson",
  lessonSlug: (slug: string) => `/lesson/${(slug || "").toLowerCase()}`,
  venue: "/venue",
  boardFree: "/board/free",
  outline: "/outline",
  board: (slug: string) => `/board/${(slug || "").toLowerCase()}`,
  boardPost: (slug: string, postId: string) => `/board/${(slug || "").toLowerCase()}/${postId}`,
  boardCompetitionInquiry: "/board/competition-inquiry",
  boardLessonInquiry: "/board/lesson-inquiry",
  apply: (competitionId: string) => `/apply/${competitionId}`,
  tournament: "/tournament",
  tournamentId: (competitionId: string) => `/tournament/${competitionId}`,
  login: "/login",
  signup: "/signup",
  findId: "/find-id",
  findPw: "/find-pw",
  my: "/my",
  myEdit: "/my/edit",
  myInquiry: (postId: string) => `/my/inquiry/${postId}`,
  admin: "/admin",
  adminLogin: "/admin/login",
  adminCompetitions: "/admin/competitions",
  adminCompetitionsId: (id: string) => `/admin/competitions/${id}`,
  adminCompetitionsNew: "/admin/competitions/new",
  adminCompetitionsOutline: "/admin/competitions/outline",
  adminBoards: "/admin/boards",
  adminBoardsSlug: (slug: string) => `/admin/boards/${(slug || "").toLowerCase()}`,
  adminLessons: "/admin/lessons",
  adminLessonsId: (id: string) => `/admin/lessons/${id}`,
  adminLessonsNew: "/admin/lessons/new",
  adminParticipants: "/admin/participants",
  adminParticipantsId: (competitionId: string) => `/admin/participants/${competitionId}`,
  adminMembers: "/admin/members",
  adminMembersId: (id: string) => `/admin/members/${id}`,
  adminBroadcast: "/admin/broadcast",
  adminSettings: "/admin/settings",
  adminAccount: "/admin/account",
  notificationsPopup: "/notifications-popup",
} as const;
